services:
  shared_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${SHARED_DB_USER}
      POSTGRES_PASSWORD: ${SHARED_DB_PASSWORD}
      POSTGRES_DB: ${SHARED_DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - ivu_shared_db_data:/var/lib/postgresql/data

  operations_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${OPERATIONS_DB_USER}
      POSTGRES_PASSWORD: ${OPERATIONS_DB_PASSWORD}
      POSTGRES_DB: ${OPERATIONS_DB_NAME}
    ports:
      - '5434:5432'
    volumes:
      - ivu_operations_db_data:/var/lib/postgresql/data

volumes:
  ivu_shared_db_data:
  ivu_operations_db_data:
